---@meta

local M = {};

---@class helpview.preview
---
--- Enables *preview* when attaching to new buffers.
---@field enable? boolean
--- Enables `hybrid mode` when attaching to new buffers.
---@field enable_hybrid_mode? boolean
---
--- Icon provider.
---@field icon_provider?
---| "internal" Internal icon provider.
---| "devicons" `nvim-web-devicons` as icon provider.
---| "mini" `mini.icons` as icon provider.
---
--- Callback functions.
---@field callbacks? preview.callbacks
--- VIM-modes where `hybrid mode` is enabled.
---@field hybrid_modes? string[]
--- Options that should/shouldn't be previewed in `hybrid_modes`.
---@field ignore_previews? preview.ignore
--- Clear lines around the cursor in `hybrid mode`, instead of nodes?
---@field linewise_hybrid_mode? boolean
--- VIM-modes where previews will be shown.
---@field modes? string[]
---
--- Debounce delay for updating previews.
---@field debounce? integer
--- Buffer filetypes where the plugin should attach.
---@field filetypes? string[]
--- Buftypes that should be ignored(e.g. nofile).
---@field ignore_buftypes? string[]
--- Condition to check if a buffer should be attached or not.
---@field condition? fun(buffer: integer): boolean
--- Maximum number of lines a buffer can have before switching to partial rendering.
---@field max_buf_lines? integer
---
--- Lines before & after the cursor that is considered being edited.
--- Edited content isn't rendered.
---@field edit_range? [ integer, integer ]
--- Lines before & after the cursor that is considered being previewed.
---@field draw_range? [ integer, integer ]
---
--- Window options for the `splitview` window.
--- See `:h nvim.open_win()`.
---@field splitview_winopts? table


--- Controls which items are affected by `hybrid_mode`.
---@class preview.ignore
---
---@field vimdoc? ignore_vimdoc[]


---@alias ignore_vimdoc
---| "arguments"
---| "code_blocks"
---| "headings"
---| "highlight_groups"
---| "horizontal_rules"
---| "inline_codes"
---| "keycodes"
---| "modelines"
---| "notes"
---| "optionlinks"
---| "tags"
---| "taglinks"
---| "urls"
---
---| "!arguments"
---| "!code_blocks"
---| "!headings"
---| "!highlight_groups"
---| "!horizontal_rules"
---| "!inline_codes"
---| "!keycodes"
---| "!modelines"
---| "!notes"
---| "!optionlinks"
---| "!tags"
---| "!taglinks"
---| "!urls"


---@class preview.callbacks
---
--- Called when attaching to a buffer.
---@field on_attach? fun(buf: integer, wins: integer[]): nil
--- Called when detaching from a buffer.
---@field on_detach? fun(buf: integer, wins: integer[]): nil
---
--- Called when disabling preview of a buffer.
--- Also called when opening `splitview`.
---@field on_disable? fun(buf: integer, wins: integer[]): nil
--- Called when enabling preview of a buffer.
--- Also called when disabling `splitview`.
---@field on_enable? fun(buf: integer, wins: integer[]): nil
---
--- Called when disabling hybrid mode in a buffer.
--- > Called after `on_attach` when attaching to a buffer.
--- > Called after `on_disable`.
---@field on_hybrid_disable? fun(buf: integer, wins: integer[]): nil
--- Called when enabling hybrid mode in a buffer.
--- > Called after `on_attach`(if `hybrid_mod` is disabled).
--- > Called after `on_enable`.
---@field on_hybrid_enable? fun(buf: integer, wins: integer[]): nil
---
--- Called when changing VIM-modes(only on active buffers).
---@field on_mode_change? fun(buf: integer, wins: integer[], mode: string): nil
---
--- Called before closing splitview.
---@field on_splitview_close? fun(source: integer, preview_buf: integer, preview_win: integer): nil
--- Called when opening splitview.
---@field on_splitview_open? fun(source: integer, preview_buf: integer, preview_win: integer): nil
---
--- Called when opening `:Help`(:H).
---@field on_help_open? fun(preview_buf: integer, preview_win: integer, overlay_buf: integer, overlay_win: integer): nil

return M;
